# Generated by Django 2.1.7 on 2019-03-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('sentence', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_number', models.IntegerField()),
                ('sentences', models.TextField(blank=True)),
            ],
        ),
    ]
