# Generated by Django 2.1.7 on 2019-03-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='name',
            new_name='title',
        ),
    ]
